truncate table products;

insert into products (code, name, category, description, image_url, price)
values ('BGS', 'Bacalhau a Gomes de Sa', 'Main Course',
        'A classic Portuguese casserole made with salted cod, thinly sliced potatoes, onions, and olives, baked to perfection and bursting with comforting flavors.',
        'https://leitesculinaria.com/wp-content/uploads/2022/12/bacalhau-gomes-de-sa.jpg', 20),
       ('PDN', 'Pastel de Nata', 'Desert',
        'Golden, flaky custard tarts with a creamy egg filling and a touch of caramelized sweetness, a beloved Portuguese treat.',
        'https://leitesculinaria.com/wp-content/uploads/2020/12/pasteis-de-nata-11-18-reader.jpg', 1.2),
       ('PAT', 'Porco Alentejana', 'Main Course',
        'Tender marinated pork shoulder and briny clams simmered in a rich white wine and red pepper sauce, served with crusty bread.',
        'https://leitesculinaria.com/wp-content/uploads/2022/10/portuguese-pork-clams-porco-alentejana.jpg', 15),
       ('CLV', 'Caldo Verde', 'Starter',
        'A hearty soup made with potatoes, chouriço sausage, and finely sliced collard greens, a comforting Portuguese classic.',
        'https://leitesculinaria.com/wp-content/uploads/2021/01/caldo-verde.jpg', 5),
       ('FJD', 'Feijoada', 'Main Course',
        'A rich and flavorful bean stew with sausage, ham, and an assortment of vegetables, served with warm rolls for the perfect comfort meal.',
        'https://leitesculinaria.com/wp-content/uploads/2021/09/portuguese-bean-soup.jpg', 12.5),
       ('ABP', 'Amêijoas à Bulhão Pato', 'Main Course',
        'Fresh clams sautéed in garlic, cilantro, and vinho verde, served with crusty bread to soak up the delicious sauce.',
        'https://leitesculinaria.com/wp-content/uploads/2021/05/portuguese-clams-vinho-verde.jpg', 12),
       ('CRZ', 'Chouriço', 'Starter',
        'Smoky, cured Portuguese sausage, perfect for sharing or pairing with cheese and bread.',
        'https://leitesculinaria.com/wp-content/uploads/2022/03/portuguese-chourico-hanging.jpg', 5),
       ('BFN', 'Bifanas', 'Starter',
        'Juicy marinated pork slices simmered in white wine and garlic, served in a soft roll with mustard and piri-piri sauce.',
        'https://leitesculinaria.com/wp-content/uploads/2020/06/bifanas-1.jpg', 4),
       ('PCA', 'Carne Assada', 'Main Course',
        'Slow-braised beef with red potatoes, chouriço, and onions, served tender and full of rich, savory flavors.',
        'https://leitesculinaria.com/wp-content/uploads/2021/04/portuguese-carne-assada.jpg', 12),
       ('ARZ', 'Arroz Doce', 'Desert',
        'Creamy rice pudding infused with citrus and cinnamon, topped with pistachios for a delightful dessert or breakfast treat.',
        'https://leitesculinaria.com/wp-content/uploads/2022/10/portuguese-rice-pudding.jpg', 5),
       ('FRB', 'Francesinha', 'Main Course',
        'A towering sandwich filled with cured meats, smothered in melted cheese, and drenched in a spicy beer-based sauce.',
        'https://leitesculinaria.com/wp-content/uploads/2022/10/francesinha.jpg', 18.9),
       ('PES', 'Pescada Cozida', 'Main Course',
        'Delicately poached hake served with boiled potatoes, carrots, and a drizzle of olive oil and vinegar.',
        'https://leitesculinaria.com/wp-content/uploads/2022/10/pescada-cozida.jpg', 14),
       ('ALE', 'Alheira', 'Starter',
        'A garlicky Portuguese sausage made with game meat, served grilled and paired with a fried egg and crispy potatoes.',
        'https://leitesculinaria.com/wp-content/uploads/2022/10/alheira.jpg', 8),
       ('BOL', 'Bolinhos de Bacalhau', 'Starter',
        'Crispy codfish fritters with a fluffy interior, perfect as a starter or snack.',
        'https://leitesculinaria.com/wp-content/uploads/2022/10/bolinhos-de-bacalhau.jpg', 6),
       ('TOR', 'Torta de Laranja', 'Desert',
        'A moist and zesty orange roll cake, bursting with citrus flavor and a delightful sweetness.',
        'https://leitesculinaria.com/wp-content/uploads/2022/10/torta-de-laranja.jpg', 7)
;