name: "microservices-skeleton"
services:
  catalog-service:
    image: rueloparentedev/restaurant-menu-service
    container_name: menu-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:postgresql://menu-db:5432/postgres
      - DC_USERNAME=postgres
      - DB_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "8081:8081"
    restart: unless-stopped
    depends_on:
      menu-db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700mb

  order-service:
    image: rueloparentedev/restaurant-order-service
    container_name: order-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - ORDERS_MENU_SERVICE_URL=http://menu-service:8081
      - DB_URL=jdbc:postgresql://orders-db:5432/postgres
      - DC_USERNAME=postgres
      - DB_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - RABBITMQ_HOST=restaurant-rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    ports:
      - "8082:8082"
    restart: unless-stopped
    depends_on:
      orders-db:
        condition: service_healthy
      restaurant-rabbitmq:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700mb

  notification-service:
    image: rueloparentedev/restaurant-notification-service
    container_name: notification-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - RABBITMQ_HOST=restaurant-rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
    ports:
      - "8083:8083"
    restart: unless-stopped
    depends_on:
      mailhog:
        condition: service_started
      restaurant-rabbitmq:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700mb