name: "microservices-skeleton"
services:
  catalog-service:
    image: rueloparentedev/restaurant-menu-service
    container_name: menu-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:postgresql://menu-db:5432/postgres
      - DC_USERNAME=postgres
      - DB_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "8081:8081"
    restart: unless-stopped
    depends_on:
      menu-db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700mb